spring.application.name=Suporte Técnico de Internet (STI)

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/DB_ITS_3}
spring.datasource.username=${DB_USERNAME:SITS_DBA}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true